language: node_js
node_js:
  - '9.10.0'
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn -v
  - npm i -g npm
install:
  - yarn add --dev --ignore-scripts babel-cli
  - yarn --ignore-scripts
script:
  - yarn lintfix
  # - yarn coverage
  - yarn build
  # - npm version patch
  # - git push
  # - git push --tags
before_deploy: "echo 'ready? LETS DO IIITT!!!'"
deploy:
  provider: npm
  email: "pablohpsilva@gmail.com"
  api_key: "5e15eb4f-4635-4fdb-acd9-c1dd81a0c79a"
  on:
    tags: true
    branch: master
branches:
  only:
    - master
    - release*
